name: Build Informant Toolchain

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out informant-toolchains
        uses: actions/checkout@v7
        with:
          path: informant-toolchains

      - name: Check out Inweb 7.2.0
        uses: actions/checkout@v7
        with:
          repository: interactivefiction/inweb
          ref: inweb-7.2.0
          path: inweb

      - name: Check out Intest 2.1.0
        uses: actions/checkout@v7
        with:
          repository: interactivefiction/intest
          ref: intest-2.1.0
          path: intest

      - name: Check out Inform 10.1.2
        uses: actions/checkout@v7
        with:
          repository: interactivefiction/inform
          ref: inform-10.1.2
          path: inform

      - name: Show build workspace
        run: |
          echo "Current directory:"
          pwd

          echo
          echo "Workspace contents:"
          ls -la

          echo
          echo "Inweb:"
          git -C inweb branch --show-current

          echo
          echo "Intest:"
          git -C intest branch --show-current

          echo
          echo "Inform:"
          git -C inform branch --show-current

      - name: Build Inweb
        run: |
          bash inweb/scripts/first.sh linux

      - name: Build Intest
        run: |
          bash intest/scripts/first.sh

      - name: Build Inform
        run: |
          cd inform
          bash scripts/first.sh

      - name: Test Inblorb
        run: |
          cd inform
          inblorb/Tangled/inblorb -help

      - name: Test Inform with Intest
        run: |
          cd inform
          ../intest/Tangled/intest inform7 -show Acidity

      - name: Run Inform test suite
        run: |
          cd inform
          make check
